### ISSUE TITLE
When Content-Type header is not mentioned, infer from `format:`

### ISSUE THREAD

**Issue by tejesh95** [gramener/gramex#115]
```yaml
    formhandler-flags:
      pattern: /$YAMLURL/flags
      handler: FormHandler
      kwargs:
        url: $YAMLPATH/flags.csv
        formats:
          pptx-table:
            format: pptx
            source: $YAMLPATH/input.pptx
            change-table:
              Table:
                table:
                  data: data['data']
            headers:
              Content-Type: application/vnd.openxmlformats-officedocument.presentationml.presentation
```

Because `format: pptx` is given, Content-Type can be optional and if not given, infer from `pptx` format mentioned.
