### ISSUE TITLE
Add SMS services to alerts

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#13]
### Summary

Alerts should be able to send SMS notifications, apart from emails

### Benefits

- Developers get a flexible way 
- Users can be notified either on SMS or on email

### Usage

The *same* alert should be able to send SMS and email notifications (based on the same conditions, data, etc.) This can be enabled via:

```yaml
kwargs:
  sms_service: ...
  sms_to: ...
  sms_subject: ...    # Which defaults to subject
  sms_sender: ...
```

This needs to be logged as well. Plan a consistent logging mechanism.

- Source: <https://code.gramener.com/cto/gramex/issues/328>
- Author: [s.anand](https://code.gramener.com/s.anand)
- Created: Sun 25 Feb 2018 03:01
