### ISSUE TITLE
FormHandler edits does not support parameters

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/gramex#134]
```yaml
url:
  gramex-data:
    pattern: /$YAMLURL/data/(.*)
    handler: FormHandler
    kwargs:
      url: $YAMLPATH/{_0}.csv
      id: ID
```

`GET 'data/flags'` returns data fine.

However, 

```javascript
$.ajax('data/flags', {
  method: 'POST',
  data: {ID: 'XXX', Name: 'Country 1', Text: 'Text ' + Math.random()}
})
```
Does NOT append a record to `flags.csv`. Instead, creates a `{_0}.csv` file, because, `url` is `$YAMLPATH/{_0}.csv` not substituted.

This can be fixed as part of #94 

@sanand0 -- should we take care of parameter substitution in `data.py` or instead `formhandler` setup? Former would mean for each of the CRUD methods.
