### ISSUE TITLE
gramextest should allow testing table content

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#147]
This takes each row in the `table.network-results` table, and each cell within that. It constructs a table of the text content. This is compared as-is with `network-results.csv`

```yaml
uitest:
  - table:
      url: network-results.csv
      row: table.network-results tr
      col: td
```

Optionally, you can specify rows or columns explicitly as a list. For example:

```yaml
  - table:
      url: network-results.csv
      row: table.network-results tr
      col:
        - td:nth-child(1)
        - td div.second_number
        - [td img, src]       # Get src= attribute from the img. Defaults to .text
        - td div.fourth_number
        - td:nth-child(3)     # as the fifth number
```

This creates a 5-column table. The col: list defines each column. Gramextest picks the first matching selector within the row, and uses the .text value (or specified attribute).
