### ISSUE TITLE
FormHandler Error Messages in Response

### ISSUE THREAD

**Issue by Ranjith-p-here** [gramener/gramex#189]
FormHandler returns SQL error messages in response. The status code is 500 ProgrammingError followed by the error details.

![image](https://user-images.githubusercontent.com/16645664/62691360-2672f800-b9ec-11e9-81b8-6dabee308ef3.png)

**Comment by pratapvardhan** [comment]
One option is to use custom error functions, like

```python
# errors.py
import gramex.cache
from pathlib import Path

folder = Path().absolute()

def error_fn(status_code, kwargs, handler):
    handler.set_status(status_code)
    tmpl = gramex.cache.open(folder / 'error.html', 'template')
    return tmpl.generate(kwargs=kwargs)
```

```yaml
handlers:
  BaseHandler:
    error:
      500: &ERROR
        function: errors.error_fn(status_code, kwargs, handler)
        headers:
          Cache-Control: no-cache
          Content-Type: text/html
      400: *ERROR
      405: *ERROR
      # .... other errors

url:
  formhandler:
    pattern: /formhandler
    handler: FormHandler
    kwargs:
      url: sqlite:///database.sqlite3
      query: 'SELECT * FROM flags LIMI 10'
```
