### ISSUE TITLE
Can't run Gramex after pip install on mac os x catalina

### ISSUE THREAD

**Issue by Gunnvant** [gramener/gramex#206]
I installed gramex as per the instructions here https://learn.gramener.com/guide/install/. When I try to run gramex I get the following error
```DEBUG   25-Nov 15:08:10 config PORT Loading config: /Users/gunnvantsaini/miniconda3/envs/gramex/lib/python3.7/site-packages/gramex/apps.yaml```
```ERROR   25-Nov 15:08:10 install PORT guide: no directory /Users/gunnvantsaini/Library/Application Support/Gramex Data/apps/guide```
I checked the path, there is no apps/guide directory. The apps.yml looks as follows:
```
capture:
    target: $GRAMEXPATH/apps/capture/
guide:
    target: $GRAMEXDATA/apps/guide/
    url: https://github.com/gramexrecipes/gramex-guide/archive/v1.57.0.zip
gramex-update:
    target: $GRAMEXPATH/apps/update/
logviewer:
    target: $GRAMEXPATH/apps/logviewer/
mail:
    target: $GRAMEXPATH/apps/mail/
smartalerts:
    target: $GRAMEXPATH/apps/smartalerts/
```
Can you please help.
