### ISSUE TITLE
Add support for user preferences

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#251]
Here is a possible implementation:

```yaml
url:
  preferences:
    pattern: /$YAMLURL/preferences
    handler: FunctionHandler
    kwargs:
      function: gramex.preferences(namespace='my-app-preferences')
```

REST API:

```
GET /preferences         # Return user preferences as a dict
PUT /preferences?x=1     # Set user preference for x to 1
GET /preferences?x       # Return user preference for x a single value
```

Python interface:

```python
prefs = gramex.preference_store(namespace='my-app-preferences')
prefs['x'] = 1
print(prefs['x'])
```
