### ISSUE TITLE
DriveHandler: Add Folder or Drives Dynamically 

### ISSUE THREAD

**Issue by nikhilkabbin** [gramener/gramex#282]
Extend DriveHandler API to dynamically add/remove drives/folder

**Comment by sanand0** [comment]
@nikhilkabbin Any suggestions on what the API might look like? It'd also help if you could share the use case for everyone's reference.

cc: @jaidevd

**Comment by jaidevd** [comment]
One usecase from IDE is as follows:

Whenever a user creates a project, we need to allow them to CRUD files. We can use DriveHandler but it should _not_ be added to the project itself. We need a programmable DriveHandler in the parent app. I'm imagining something like:

```yaml
# IDE/gramex.yaml
url:
  pattern: /$YAMLURL/(?P<username>)/(?P<project>.*)/drive
  handler: DriveHandler
  kwargs:
    path: $GRAMEXAPPS/IDE/{{ username }}/{{ projects }}/uploads
```

**Comment by jaidevd** [comment]
This is relatively easier to do with `UploadHandler`. This is my config:
```yaml
ide-upload-handler:
    pattern: /$YAMLURL/upload/(.*)
    handler: ide.IDEUploadHandler
    kwargs:
      path: $GRAMEXDATA/IDE/uploads
```

And this is the subclassed UploadHandler:

```python
class IDEUploadHandler(UploadHandler):

    def prepare(self, *args, **kwargs):
        path = op.join(IDE_ROOT, self.current_user.email, self.path_args[0], 'uploads')
        self.uploader = FileUpload(path=path, keys=None)
        super(IDEUploadHandler, self).prepare(*args, **kwargs)
```

@sanand0 would something like this work for `DriveHandler`? I didn't touch it because there `path` is a class attribute, and there doesn't seem to be one place where I can just hack it. In `UploadHandler`, on the other hand, the `uploader` attribute (which is an instance attribute) is the only thing that seems to depend on the path.
