### ISSUE TITLE
Deploy secrets

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#284]
- [x] Running `secrets KEY1 KEY_* KEY=VALUE` in the Gitlab / Travis CI saves specified environment variables in a file.
    - Saves by default into `$PWD/.secrets.yaml`
    - By convention can be at `$GRAMEXDATA/.secret.<app-folder>.yaml`, eg. `$GRAMEXDATA/.secret.gramex-v1-8030.yaml` by specifying `secrets -o path`
    - If the file already has the key, it is overwritten with a INFO log.
- [x] Gramex updates all environment variables from `$PWD/.secrets.yaml`
    - These are updated into os.environ -- first thing when Gramex loads, _before_ loading gramex.yaml
    - If there is a key called `GRAMEX_SECRETS_URL:`, secrets from that URL are fetched, decrypted using the cookie_secret, and updated into the environment. This may allow changing secrets remotely without access to the server
    - Change in secrets require a restart
    - If an environment variable is over-written, it is logged as a warning (printing only the key, not value).
- [x] Create a tool on the Gramex guide that can encrypt secrets using a secret cookie and return the encrypted text. 
- [ ] Document process for Gitlab, Travis, Jenkins, Github actions, Circle CI on the guide

Sample `.gitlab-ci.yaml`

```yaml
deploy:
  stage: deploy
  script:
    # Save AWS_KEY, AWS_SECRET, and all GOOGLE_ env vars into .secrets.yaml in current directory
    - secrets AWS_KEY AWS_SECRET GOOGLE_* GRAMEX_SECRETS_URL=https://gist.github.com/...
    - deploy
  only: [master, dev, /^dev-.*$/]
  variables:
    SERVER: gramener.com
    URL: app-name
    SETUP: yarn install
````

Sample .secrets.yaml

```yaml
AWS_KEY: ...
AWS_SECRET: ...
```

or 

```yaml
GRAMEX_SECRETS_URL: https://gist.github.com/...
```
