### ISSUE TITLE
Convert any function into a request handler

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#304]
Add a decorator which converts any function to work with a `handler` object.

Suppose we have:
```python
@make_handlerfunc('GET')
def add(x, y, z=42):
   return x + y + z

@make_handlerfunc('POST')
def greet(name):
    return f"Hello, {name}!"
```

then, this would become equivalent to:
```python
def wrapped_func(handler):
    args = handler.path_args
    if handler.request.method == "GET":
        kwargs = handler.query_params  # or whatever
    elif handler.request.method == 'POST':
        kwargs = handler.request_body_args
    return original_func(*args, **kwargs)
```

That way, I can add `add` or `greet` directly in my application config:
```yaml
foo:
  pattern: /$YAMLURL/(.*)/(.*)
  handler: FunctionHandler
  kwargs:
    # Note that this is `add` as defined above.
    # By itself, it won't work, but the `make_handlerfunc` wrapper makes it work.
    function: mymodule.add
```

For now, we can enforce that only functions which return a JSON-able object will work with this. Let's also generally assume that it's the user's responsibility to make the wrapped function otherwise RESTful.

We will only infer whatever we can from function signatures (args, kwargs) and type hints. We will also force `json.dumps` the output.

**Comment by sanand0** [comment]
Agreed. Let's do this. Would you like to implement this, @jaidevd?

**Comment by jaidevd** [comment]
Yes, @sanand0 I'll send a PR on Wednesday.

**Comment by jaidevd** [comment]
@sanand0 , this is a minimal example:
```python
class MockHandler(object):
    def __init__(self, path_args=None, urlparams=None, body=None,
                 method='GET'):
        if not path_args:
            path_args = []
        self.path_args = path_args
        if not urlparams:
            urlparams = {}
        self.urlparams = urlparams
        self.body = body
        self.method = method


def decorator(func):
    def wrapper(handler):
        pargs = handler.path_args
        if handler.method == 'GET':
            kwargs = handler.urlparams
        elif handler.method == 'POST':
            kwargs = handler.body
        return func(*args, **kwargs)
    return wrapper


@decorator
def _add(a, b):
    return a + b


if __name__ == '__main__':
    handler = MockHandler(path_args=[1, 2])
    # Now this works with a handler:
    print(_add(handler))  # 3
```

Now we just generalize the decorator until it works with most cases.

**Comment by sanand0** [comment]
Thanks @jaidevd. Suppose I have this function signature: `def calc(x: float, operation: str, y: float)`,

1. Could I just call `/calc?x=2&operation=*&y=3.5`?
2. How can I limit operations to `+`, `-`, etc via automated type detection?

Also curious what we can learn from https://fastapi.tiangolo.com/

**Comment by jaidevd** [comment]
@sanand0, to your first point, yes, that's exactly what you should be able to do, as follows:

`gramex.yaml`
```yaml
url:
        calc:
                pattern: /$YAMLURL/calc
                handler: FunctionHandler
                kwargs:
                        function: calc.calc
                        headers:
                                Content-Type: application/json
```

`calc.py`
```python
from typing import get_type_hints
from functools import wraps
import json


def decorator(func):
    @wraps(func)
    def wrapper(handler):
        args = handler.path_args
        if handler.request.method == 'GET':
            kwargs = {k: v[0] for k, v in handler.args.items()}
        elif handler.method == 'POST':
            kwargs = handler.body
        hints = get_type_hints(func)
        for arg, argtype in hints.items():
            kwargs[arg] = argtype(kwargs[arg])
        return json.dumps(func(*args, **kwargs))
    return wrapper


# This is fishy
@decorator
def calc(x: float, operation: str, y: float):
    code = f'{x} {operation} {y}'
    return eval(code)
```

To the second point, we can't limit the `operation` arg to only `{+, -, etc}` since it's typed as an `str`. If it was an Enum-like type, we could enforce it.
