### ISSUE TITLE
DriveHandler multi-drive always downloads files from the first drive

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#323]
**Is something not working as expected?**
When using DriveHandler with multiple drives, the downloads are always from the first drive

**Steps to reproduce.**
Create this `gramex.yaml`
```yaml
import:
  ui:
    path: $GRAMEXAPPS/ui/gramex.yaml
    YAMLURL: $YAMLURL/ui/
  filemanager:
    path: $GRAMEXAPPS/filemanager/gramex.yaml
    YAMLURL: $YAMLURL/filemanager/
    FILEMANAGER_KWARGS:
      drives: ['drive1', 'drive2', 'drive3']
      title: "DriveHandler Test"

url:
  drive1:
    pattern: /$YAMLURL/drive1
    handler: DriveHandler
    kwargs:
      path: $YAMLPATH/drive1/
  drive2:
    pattern: /$YAMLURL/drive2
    handler: DriveHandler
    kwargs:
      path: $YAMLPATH/drive2/
  drive3:
    pattern: /$YAMLURL/drive3
    handler: DriveHandler
    kwargs:
      path: $YAMLPATH/drive3/
```

Visit `/filemanager` and upload files into each drive. Download a file from the 2nd or 3rd drive. It downloads the corresponding file from the first drive, i.e. `/drive1?id=1` instead of `/drive2?id=2`

**Expected behavior**

The selected file from the **selected drive** should be downloaded.

**Your environment:**
 - OS: any
 - Browser: any
 - Python version: any
 - Gramex version: 1.65.0

**Additional context**
Raised by @nikhilkabbin
