### ISSUE TITLE
gramex.transforms.handler does not have an option to pass handler to the function

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#331]
**Is something not working as expected?**

I want this gramex.yaml:

```yaml
  func/content:
    pattern: /func/content/(\d+)\.(txt|json)
    handler: FunctionHandler
    kwargs:
      function: functionutils.content
```

to run `functionutils.content(x: int, y: str)`. The output should have a `Content-Type: application/json` if I pass `/func/content/123.json` but a `Content-Type: text/plain` if I pass `/func/content/123.txt`.

This is possible only if `functionutils.content` can access `handler` -- but there's no way to pass that.

**Steps to reproduce.**
`gramex.yaml` is as above. `functionutils.py` is below:

```python
from gramex.transforms import handler

@handler
def content(x: int, y: str, handler):
    if y == 'json':
        handler.set_header('Content-Type', 'application/json')
        return json.dumps({'x': x}, separators=(',', ':'))
    elif y == 'txt':
        handler.set_header('Content-Type', 'text/plain')
        return f'x={x}'
```

Visit `/func/content/123.json` and `/func/content/123.txt`. This will raise an Exception

**Expected behavior**
The output should have a `Content-Type: application/json` if I pass `/func/content/123.json` but a `Content-Type: text/plain` if I pass `/func/content/123.txt`.

**Your environment:**
 - OS: Windows
 - Browser: Chrome
 - Python version: 3.7
 - Gramex version: 1.65
