### ISSUE TITLE
Forms builder - Publish as a Gramex app

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#335]
**Is your feature request related to a problem? Please describe.**
This is related to and a sub-feature of #324.

**Describe the solution you'd like**
- [ ] import forms as a gramex app

```yaml
import:
  forms:
    path: $GRAMEXPATH/forms/gramex.yaml
    YAMLURL: $YAMLURL/forms/
```

**Describe alternatives you've considered**
NA

**Additional context**
NA
