### ISSUE TITLE
Allow importing bootstrap-theme.scss in SASS, and rendering .scss files via FileHandler

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#340]
**Is your feature request related to a problem? Please describe.**
Currently, [bootstrap-theme.scss](https://github.com/gramener/gramex/blob/master/gramex/apps/ui/bootstrap-theme.scss) is a Tornado template, and cannot be imported into SASS.

Further, the way we configure these is via `style.css` using `bootstraptheme.css?primary=%23123456&...` which is harded to read than `primary: #123456`. 

@pratapvardhan mentioned that these are roadblocks.

**Describe the solution you'd like**
- [ ] Convert `bootstrap-theme.scss` into a pure SCSS file
- [ ] Allow UI components to be imported with default variables, e.g.

```yaml
  ui:
    path: $GRAMEXAPPS/u/gramex.yaml
    YAMLURL: $YAMLURL/ui/
    UI_VARS:
      primary: '#123456'
```
- [ ] Allow `gramex.apps.ui.sass` (or a newer version of the function) to compile SASS files WITHOUT allowing Tornado templates
- [ ] Allow FileHandler to support SCSS compilation via: `scss: *.scss` -- just like `template: *.html` is allowed
