### ISSUE TITLE
Support forward slashes in JSONHandler keys?

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#419]
**Is your feature request related to a problem? Please describe.**
In the IDE we're using JSONHandler to read and write config from Yaml files. Sometimes, configs are written as follows:
```yaml
url:
    process-monitor/home:
       pattern: ...
       handler: ...
```
This happens especially when working on existing projects. 

The URL key here is `process-monitor/home`. Suppose I want to change the pattern of this handler, I can't `PUT` to it with JSONHandler because the request goes to `process-monitor/home`. And that, as expected, creates a structure like
```yaml
process-monitor:
  home:
     pattern: /newpattern/
     handler: ...
```
and leaves the original entry unchanged.

**Describe the solution you'd like**
Suppose the client ensures that any slashes that are supposed to be inside a key are properly escaped, can JSONHandler manage them on its end too?
