### ISSUE TITLE
GRAMEX-87 ⁃ docker image build fails

### ISSUE THREAD

**Issue by shraddheya** [gramener/gramex#448]
**Is something not working as expected?**
 Line 8 : in DockerFile: `RUN apt update && apt install -y pandoc`
 Might halt and even crash the docker image build because `update` is not passed `-y` (crashes always for me)

 ### **_SOLUTION_**
`RUN apt -y --allow-releaseinfo-change update && apt install -y pandoc`

**Steps to reproduce.**
Please help us reproduce the bug, by sharing:
`docker-compose.yml` : 

```yaml
version: "3.9"
services:
  galaxy:
    build: .
    tty: true
    ports:
      - 9988:9988
```

`docker-compose rm; docker-compose pull ; docker-compose build --no-cache; docker-compose up -d`

**Expected behavior**
Must build the image from dockerfile.

**Your environment:**

* Ubuntu 20.04
* Win 10 Pro

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-87)
