### ISSUE TITLE
GRAMEX-90 ⁃ FormHandler query not working with MongoDB

### ISSUE THREAD

**Issue by nikhilkabbin** [gramener/gramex#451]
**Is something not working as expected?**
FormHandler query not working

**Steps to reproduce.**

1. Gramex Configuration:

```
  mongodb-formhandler:
    pattern: /$YAMLURL/data
    handler: FormHandler
    kwargs:
      industry:
        url: $mongo_db_connection
        database: database-name
        collection: collection-name
        query: '{"industry": "value"}'
        xsrf_cookies: false
        id: id
```

1. Error:
    a. If query is passed as string:
    ![image](https://user-images.githubusercontent.com/2226671/134449127-55fc42a4-b5c9-4ec5-9fda-a7fd4c9ac35c.png)

b. If query is passed as dict:

![image](https://user-images.githubusercontent.com/2226671/134449221-416a506f-436a-4ea7-87a0-9d18f6ec3b1d.png)

**Expected behavior**
Return data based on custom query

**Your environment:**

* OS: Windows
* Python version: 3.7
* Gramex version: 1.72

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-90)

**Comment by sanand0** [comment]
@nikhilkabbin  -- could you please check with the master branch if you still have this issue?

**Comment by sanand0** [comment]
I tested with the following configuration, and it works. Closing the issue. 

Please note that `query:` is not a string -- it's an object.

```yaml
url:
  mongodb-formhandler:
    pattern: /$YAMLURL/data
    handler: FormHandler
    kwargs:
      industry:
        url: mongodb://localhost:27017
        database: testdatabase
        collection: testcollection
        query: {"SOP": 4, "LOR": 4}
        xsrf_cookies: false
        id: Name
```
