### ISSUE TITLE
GRAMEX-102 ⁃ url: without pattern: crashes Gramex

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#461]
Create a gramex.yaml with:

```yaml
url:
  invalid:
    patern: something   # Note the incorrect spelling of pattern
    handler: CaptureHandler
```

This should log an error and Gramex should run the remaining handlers. Instead, none of the handlers are exposed.

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-102)
