### ISSUE TITLE
FormHandler access control

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#48]
FormHandler should allow only specific users to perform specific database actions. For example:

- Some users can only read from a table
- Some users can only read certain columns, or edit certain columns

This requires identifying the users, and identifying their permissions. FormHandler (and `gramex.data.filter`) should accept an `auth` object that has 3 keys:

- `membership`: same as in [auth roles](https://learn.gramener.com/guide/auth/#roles). Defines WHO this rule is for. This is a list of attr: values that match the user object. For example:
  - `email: '*@gramener.com'` -- matches any user where `handler.current_user['email']` matches `*@gramener.com`
  - Multiple values are treated as OR conditions. `email: [x@..., y@...]` matches both `x@...` OR `y@...`
  - Multiple keys are treated as AND conditions. `[domain: gramener.com, user: s.anand]` means that `handler.current_user['user']` MUST equal s.anand AND `handler.current_user['domain']` MUST equal gramener.com`
- `conditition`: same as in [auth roles](https://learn.gramener.com/guide/auth/#roles). Defines WHO this rule is for. Typically used INSTEAD of membership if we want advanced rules / custom functions.
- `permissions`: optional list of rule objects. Defaults to all access. A rule object has:
  - `type`: allow or deny
  - `url`: DB URL to allow/deny access
  - `sheetname` or `table` or anything else `gramex.data.filter` accepts
  - `column`: columns to allow/deny access
  - `access`: type of access to allow or deny
  - values can be a string or list of strings that support `fnmatch` style wildcards

```yaml
condition: ...
membership:
    - col: val
    - col: [val, val]
permission:
    - {type: allow, url: data.db, access: [all = create, read, update, delete]}
    - {type: deny,  url: data.db, table: t1, access: [create]}
    - {type: deny,  url: data.db, table: t2, column: c1, access: [write = update, delete, create]}
```

To be implemented as `gramex.data.access(auth, ...)` that returns True / False

- Source: <https://code.gramener.com/cto/gramex/issues/610>
- Author: [s.anand](https://code.gramener.com/s.anand)
- Created: Tue 29 Jan 2019 05:31
