### ISSUE TITLE
GRAMEX-135 ⁃ ensure_single_session logs all users out

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#482]
**Is something not working as expected?**
When using [`ensure_single_session`](https://gramener.com/gramex/guide/auth/#login-actions), it logs all users out.

**Steps to reproduce.**
In Gramex 1.74, run this configuration:

```yaml
url:
  login:
    pattern: /login
    handler: SimpleAuth         # to the SimpleAuth handler
    kwargs:
      credentials:              # Specify the user IDs and passwords
        alpha: alpha            # User: alpha has password: alpha
        beta: beta              # Similarly for beta
      action:                                     # Run multiple function on Google auth
        - function: ensure_single_session         # Logs user out of all other sessions
```

Steps:

1. Log in as `alpha` in a browser window.
1. Log in as `beta` in a new incognito window.
1. `alpha` gets logged out in the main window. The console prints `dropping user alpha from session ...`

**Expected behavior**

`alpha` should never get dropped when the user logs in. 

**Your environment:**

* OS: Windows
* Browser: Chrome
* Python version: 3.7.3
* Gramex version: 1.74.0

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-135)
