### ISSUE TITLE
GRAMEX-136 ⁃ JSON store does not persist session changes

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#483]
**Is something not working as expected?**
Changes to the session, such as the URL to visit after login, do not persist across instances or restart.

**Steps to reproduce.**

Take this `gramex.yaml`

```yaml
url:
  login:
    pattern: /login
    handler: SimpleAuth         # to the SimpleAuth handler
    kwargs:
      credentials:              # Specify the user IDs and passwords
        alpha: alpha            # User: alpha has password: alpha
        beta: beta              # Similarly for beta
```

It works as expected if Gramex is running:

1. Visit `/login?next=/test`
1. In a new window, visit `/login` (without `?next=`)
1. Log in as `alpha` (password: `alpha`)
1. You're re-directed to `/test` (the file not found error is expected)

**BUT** if Gramex is restarted, midway, it redirects to `/`

1. Visit `/login?next=/newtest`
1. Wait for 5 seconds. Then **RESTART** Gramex
1. In a new window, visit `/login` (without `?next=`)
1. Log in as `alpha` (password: `alpha`)
1. You are re-directed to `/` -- not `/newtest`

**Expected behavior:**
All session information should be persisted in the session store. It is not.

This affects ANY update to the session object if there are multiple instances.

**Your environment:**

* OS: Windows
* Browser: Chome
* Python version: 3.7.3
* Gramex version: 1.74.0

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-136)
