### ISSUE TITLE
GRAMEX-137 ⁃ FileHandler does not reload templates

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#484]
**Is something not working as expected?**
FileHandler does not reload index_template without a restart

**Steps to reproduce.**

**Step 1**: Create this `gramex.yaml`

```yaml
url:
  home:
    pattern: /$YAMLURL/(.*)
    handler: FileHandler
    kwargs:
      path: $YAMLPATH/
      index: true
      index_template: $YAMLPATH/template.html
```

**Step 2**: Create this `template.html`: `<h1>$path</h1><ul>$body</ul>`

**Step 3**: Run Gramex and visit the home page. This result appears:

![image](https://user-images.githubusercontent.com/63734/146660102-933f7a5e-20af-4015-92a5-1fa7f79fb09b.png)

**Step 4**: Change `template.html` to `<h1>$path</h1><ol>$body</ol>` -- change `ul` to `ol`

**Step 3**: Reload the home page without restarting Gramex. The output remains the same. It uses `ul` instead of `ol`

**Expected behavior:**
When the index template is changed, Gramex should load from the updated template.

**Your environment:**

* OS: Windows
* Browser: Chrome
* Python version: 3.7.3
* Gramex version: 1.74.0

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-137)
