### ISSUE TITLE
GRAMEX-138 ⁃ Gramex does not reload configurations after invalid configuration

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#485]
**Is something not working as expected?**
If the `gramex.yaml` has certain invalid configurations, Gramex does not auto-reload gramex.yaml

**Steps to reproduce.**

Create this `gramex.yaml`:

```yaml
url:
  home:
    pattern: /$YAMLURL/
    handler: FunctionHandler
    kwargs:
      function: 3 + 4
```

Make the following changes:

1. Change `function: 3 + 4` to `abc`. Then change it back.
1. Change `handler: FunctionHandler` to `handler: 3`. Then change it back.
1. Change `pattern: /$YAMLURL/` to `pattern: ('. Then change it back.
1. Change `home:` to `home` (remove the last colon). Then change it back.

**Expected behavior:**

Gramex should restore the original configuration in every case. But sometimes, it does not.

**Your environment:**

* OS: Windows
* Browser: Chrome
* Python version: 3.7.3
* Gramex version: 1.74.0

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-138)
