### ISSUE TITLE
GRAMEX-153 ⁃ Gramex does not support SameSite cookies

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#500]
[SameSite cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesite) add additional security to the cookie. Security scanners like Fortify.com check for this. Let's add it like this:

```yaml
app:
  session:
    httponly: true
    secure: true
    samesite: Strict
```

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-153)
