### ISSUE TITLE
GRAMEX-167 ⁃ FileHandler should compile TypeScript (.ts) files

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#512]
This FileHandler configuration should auto-compile TypeScript files

```yaml
    handler: FileHandler
    kwargs:
      typescript: ['*.ts']
```

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-167)
