### ISSUE TITLE
GRAMEX-169 ⁃ FormHandler does not support Snowflake dialect

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#514]
When using this configuration:

```
snowflake-job:
    pattern: /$YAMLURL/dim-job
    handler: FormHandler
    kwargs:
      url: 'snowflake://user:password@HOST/DB/SCHEMA'
      table: dim_job
      query: SELECT * FROM dim_job limit 10
```

... it reports a `KeyError: 'gramex.cache.query cannot cache dialect "snowflake" yet'`

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-169)
