### ISSUE TITLE
GRAMEX-177 ⁃ OTP does not work across multiple instances

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#522]
Currently, OTP data is stored in `$GRAMEXDATA/auth.recover.db`. This is not distributed across instances.

Create an `otp:` service that accepts connection parameters, e.g. with this default

```yaml
otp:
    url: sqlite:///$GRAMEXDATA/auth.recover.db
    table: users
```

Change the `OTP` class to use this (singleton) instance instead.

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-177)
