### ISSUE TITLE
`build_transform` cannot compile sklearn estimator methods

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#539]
In MLHandler, we use [transforms](https://gramener.com/gramex/guide/mlhandler/#example-classify-overlapping-patterns-with-logistic-regression) to preprocess data. But they don't work in some cases, like:

```yaml
    handler: MLHandler
    kwargs:
      data:
        url: ...
        transform: sklearn.preprocessing.PolynomialFeatures(2).fit_transform
```

This results in the built transform being `None`.
