### ISSUE TITLE
Schedules should support an error alert

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#550]
When a schedule fails, users are unaware of it unless they look at logs.

Allow schedules to support an `error-alert:` config that specifies the error alert to call. For example:

```yaml
schedule:
  run-periodically: mymodule.myfunction()
  every: 6h
  error-alert: email-admin

alert:
    to: 'admin@example.org'
    subject: 'Gramex raised an Exception'
    body: ...
```

If there's an exception, this sends an email using the alert.
