### ISSUE TITLE
Invalid computed variable crashes Gramex

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#564]
If we have 

```yaml
variables:
    INVALID_FUNCTION:
        function: nonexistent()
```

... this prevents Gramex from starting up. It should warn and continue with the default value of the variable instead.
