### ISSUE TITLE
Enable API rate limiting

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#632]
Every handler supports rate-limiting via `ratelimit:`. For example:

```yaml
url:
  page:
    pattern: /api
    handler: FormHandler # or any handler
    kwargs:
      # ...
      ratelimit:
        keys: [daily, user]
        limit: 50
```

`keys` define how to rate-limit. It's an array of strings. Values can be `hourly`, `daily`, `weekly`, `monthly`, `user`. For example:

```yaml
# Set a weekly limit by user
        keys: [weekly, user]
# Set a daily limit globally
        keys: [daily]
```

`keys` can also be defined with functions. For example:

```yaml
# Set a daily limit by user's email domain name
        keys: [daily, {function: handler.current_user.email.split('@')[-1]}]
```

In fact, the pre-defined strings for `keys` just map to these functions:

- `hourly`: `datetime.datetime.utcnow().strftime('%Y-%m-%d %H')`
- `daily`: `datetime.datetime.utcnow().strftime('%Y-%m-%d')`
- `weekly`: `datetime.datetime.utcnow().strftime('%Y %U')`
- `monthly`: `datetime.datetime.utcnow().strftime('%Y-%m')`
- `user`: `handler.current_user.id`

`limit` is the maximum number of successful requests to the page. This can be a number or a function that returns a number. For example:

```yaml
# Set a constant limit of 50
        limit: 50
# Limit to 50 for logged-in users, 10 for others
        limit: {function: 50 if handler.current_user else 10}
```

The usage is stored in a cache whose location is defined in `app.ratelimit`:

```yaml
app:
  ratelimit:
    # Save in a JSON store
    type: json
    path: $GRAMEXDATA/ratelimit.json
    # Flush every 5 seconds
    flush: 5
    # Clear expired sessions every hour
    purge: 3600
```

On each request, Gramex computes the `keys` and `limit`, looks up usage, and sets these HTTP headers:

- `X-RateLimit-Limit`: limit
- `X-RateLimit-Remaining`: limit - usage
- `X-RateLimit-Reset`: Number of seconds before window resets. Only available for `hourly`, `daily`, `weekly` and `monthly` keys
- `Retry-After`: same as `X-Ratelimit-Reset`

If the usage exceeds the limit, Gramex raises a [HTTP 429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) response. This can be formatted via a custom error page.

If the response is successful, the usage increments by 1.
