### ISSUE TITLE
Form Handler: _offset is not working with MSSQL Server

### ISSUE THREAD

**Issue by jpsiyyadri** [gramener/gramex#65]
**_Yaml Config:_**

```yaml
  path_name:
    pattern: /$YAMLURL/urlpattern
    handler: FormHandler
    kwargs:
      auth: {login_url: /$YAMLURL/login/}
      url: $dbstring
      table: tablename
      id: [id]
```

**_url pattern:_** [localhost:9981/urlpattern?_offset=12000&_limit=15000](url)

**_Throwing this error_**

![image](https://user-images.githubusercontent.com/30207596/52354749-00799480-2a57-11e9-8a99-123ae9358f6a.png)
