### ISSUE TITLE
FormHandler must support ElasticSearch and MongoDB

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#7]
More project uses MongoDB. This warrants integration with MongoDB and ElasticSearch.

We would want to extend FormHandler API behavior which resides in `gramex.data.{filter,update,etc}` to connect to MongoDB and ElasticSearch. See [docstrings for usage](https://github.com/gramener/gramex/blob/v1.56.0/gramex/data.py#L75) and URL query parameters to understood API.

```python
filtered = gramex.data.filter('connection_string_to_detect', table='table', args=handler.args)
``` 

- Extend testcases in `testlib/test_data.py` and `tests/test_formhandler.py` for the given connector. These already have bunch of testcases, tested across different connectors, Inherit and extend for new connectors.

Approaches For ElasticSearch:
- Evaluate if `sqlalchemy-elasticquery` can be used. We directly support sqlalchemy dialects.
- See if [elasticsearch-sql](https://www.elastic.co/what-is/elasticsearch-sql) has extensive support and if we can integrate with it's ODBC driver. This would be high effort.
- Validate with existing test scenarios. 

---
- Source: <https://code.gramener.com/cto/gramex/issues/165>
- Author: [s.anand](https://code.gramener.com/s.anand)
- Created: Sun 29 Oct 2017 03:27

**Comment by jaidevd** [comment]
cc @nikhilkabbin

**Comment by bkamapantula** [comment]
- `sqlalchemy-elasticquery` isn't maintained regularly.

sharing notes from discussions with @jaidevd, @nikhilkabbin, @naveenreddymanukonda

## proposed config

```yaml
fh-endpoint:
  pattern: /$YAMLURL/data
  handler: FormHandler
  kwargs:
    url: $YAMLPATH/assets/data/data.csv

es-search:
  pattern: /$YAMLURL/es
  handler: ESHandler
  kwargs:
    prepare: mappings.prepare_args
    url: http://localhost:9200/
    # modify: project_app.modify_data
    indexes: '' or [...]          # optional if POST/PUT is defined, required otherwise
    # supported methods
    methods: [PUT, POST, DELETE, GET]
    # to add/insert into ES
    POST/PUT/DELETE:
      membership: # for specific users
      # always a bulk insert
      # source, function optional for DELETE, required otherwise
      # for document DELETE/POST we need index, document_id
      # for index DELETE/POST we need index
      one:
        index: index_name_1
        document_id: doc_id_1
        source: FH_endpoint_1
        function: mappings.custom_fn1
      two:
        index: index_name_2
        document_id: doc_id_2
        source: FH_endpoint_2
        function: mappings.custom_fn2
      ...
    # GET/query for all users
    query: "ES query"
```

# ESHandler Objectives

- reduce developer effort to configure, maintain ES

## Features
- ability to
  - download/install/configure ES
    - via proxyhandler
  - search
  - CRUD indexes
  - construct queries
    - args to ES
    - type annotation
    - complex queries
      - booleans, multi-match etc.
- extend ProxyHandler to support functions for ESHandler

gramex install elasticsearch?
