### ISSUE TITLE
FormHandler and gramex.data.filter could support table joins

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#700]
A possible syntax could be:

```yaml
    kwargs:
      url: ...
      table: sales
      # query: SELECT * FROM sales
      join:
        table: customer
        type: outer
        on:
          sales.customer: customer.id
          sales.city: customer.city
        using: [col1, col2]
```
