### ISSUE TITLE
Lookup attributes for automated logins

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#736]
Currently, [lookup attributes](https://gramener.com/gramex/guide/auth/#lookup-attributes) are added when a user logs in.

There is no mechanism of lookup attributes for [automated logins](https://gramener.com/gramex/guide/auth/#automated-logins), i.e. API keys, OTPs, etc.

To enable this, allow:

```yaml
storelocations:
  otp:
    columns:
      limit: INTEGER
      frequency: TEXT
```

This will add the `{limit: ..., frequency: ...}` keys to `handler.current_user` over-and-above what's in the `user` column.

PS: Also, ensure that the token is a primary key in this database.
