### ISSUE TITLE
Ratelimit does not accept a function to specify frequency as hourly/daily/...

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#739]
We expect the following to work:

```yaml
    ratelimit:
      keys:
        - function: 'hourly' if some_condition(handler) else 'daily'
```

But it does not treat the key as a pre-defined frequency. It treats it as the actual result of the key. This is incorrect.

Suggestion: Use a `key:` instead of `function:` to specify pre-defined keys.

```yaml
    ratelimit:
      keys:
        - key: 'hourly' if some_condition(handler) else 'daily'
```
