### ISSUE TITLE
Gramextest should wait for selector or script

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#79]
```yaml
- name: wait for 10 seconds
  wait: 10
- name: wait for 10 seconds
  wait:
    timeout: 10
- name: wait for xpath selector
  wait:
    selector: xpath //a
- name: wait for CSS selector
  wait:
    selector: a.link
- name: wait for JS to return True (by evaluating every 50ms)
  wait:
    script: '$(".link").is(":visible")'
- name: wait for selector with timeout
  wait:
    selector: ...
    timeout: ...
- name: wait for script with timeout
  wait:
    script: ...
    timeout: ...
```
