### ISSUE TITLE
Test case for database as source in smart alerts

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#83]
Current test cases cover file-based data source -- [tests/gramex.yaml](https://code.gramener.com/cto/gramex/blob/dev/tests/gramex.yaml#L2684-2709)

Sample config:

```yaml
alert:
  first-alert:
    startup: '*'
    thread: true
    data:
      from_db:
        url: mysql://user:password@localhost/database
        table: user_details
    to: user1@domain.com, user2@domain.com
    subject: Hey there {{ row.user }}!
    ...
```
