### ISSUE TITLE
gramextest values must allow variables or computations

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#85]

**Comment by rajeshp7** [comment]
Identified scenarios are
1. Store result of a database query, to compare the value with UI
2. Store result of a database query, to pass it as an input to another query
3. Store a value from a screen, to compare it with the value in another screen
4. Store a value to iterate number of times
5. Store a value to use it in regular expressions
6. store a random number to use it as an input to some functionality
7. Store an expression to validate the result for a set of values

**Comment by sanand0** [comment]
To summarise:

- variables may be sourced from the UI, data or Python expressions
- variable expressions allow accessing specific values within a list, dict, etc using the Python syntax
- variables may be used in place of any value when matching

**Comment by sanand0** [comment]
```yaml
# set-python sets the variable q to the result of a Python expression
- set-python q:
    gramex.data.filter(
        url='sqlite:///data.db',
        args={'name':['Gramener']}
    )
# Modules are implicitly imported
- set-python randnumber: random.randint(100)
# All string values are evaluted as Tornado templates, with all past variables available
- title: 'Gramener - {{ q[0]['title'] }}'
# set-js sets the variable heading to the result of a JS expression evaluated in the browser
- set-js heading: $('h1').text()
# These variables can be used when setting other values
- set-js heading: "$('.myclass').text()"                # is the same as
- set-js heading: "$('.{{ "my" + "class" }}').text()"
# They are also directly available within Python expressions
- set-python q2:
    gramex.data.filter(
        url="sqlite:///data.db",
        args={"name":[q[0]["name"]]}    # This q is a previously set variable
    )
```
