### ISSUE TITLE
gramextest should allow looping through combinations of parameters

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#88]
```yaml
  - loop:
      url: combinations:.xlsx
      run:
        - fetch: http://localhost/dashboard?channel={channel}
        - Check if all images exist
        - Check if there are any console errors
```

This loads the URL specified (`combinations.xlsx`). Optionally allow sheet_name and other parameters similar to FormHandler.

For each row in the result, it executes the steps under `run:`. Allow variable substitution within these.
