### ISSUE TITLE
FormHandler parameters substitution for options

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/gramex#94]
I'd like to expose an excel file `data.xlsx`  (with sheet names, `one`, `two`, `three`) under this spec.

```yaml
url:
  data-sheets:
    pattern: /$YAMLURL/data/(.*)
    handler: FormHandler
    kwargs:
      url: $YAMLPATH/data.xlsx
      sheet_name: '{_0}'
```

Where

- `/data/one` would fetch data from sheet `one` and so on.

Currently, I'd need to create a separate urlspec for each sheet.

**Implications:** extent parameter substitution to every first-level key under `kwargs`?

Thoughts @gramener/gramener-cto ?
